# Generated by Django 2.2 on 2020-04-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customerid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
